// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUl-wYyUNTi3axuAK0BJXU-G_gpG_KF6M',
    appId: '1:164434614544:web:7a71fcfac3f1b6d78a6d95',
    messagingSenderId: '164434614544',
    projectId: 'mmail-1e27d',
    authDomain: 'mmail-1e27d.firebaseapp.com',
    storageBucket: 'mmail-1e27d.firebasestorage.app',
    measurementId: 'G-BJDGHL3YZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwhYZNrfjNaqASOJ0jYuotMvDj0dO1zoY',
    appId: '1:164434614544:android:281deab0410069a58a6d95',
    messagingSenderId: '164434614544',
    projectId: 'mmail-1e27d',
    storageBucket: 'mmail-1e27d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qVrIM_6cDxNqQSZor0ARqAgiqSwBbKQ',
    appId: '1:164434614544:ios:e65e6d701245c5a58a6d95',
    messagingSenderId: '164434614544',
    projectId: 'mmail-1e27d',
    storageBucket: 'mmail-1e27d.firebasestorage.app',
    iosBundleId: 'com.example.mewmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2qVrIM_6cDxNqQSZor0ARqAgiqSwBbKQ',
    appId: '1:164434614544:ios:e65e6d701245c5a58a6d95',
    messagingSenderId: '164434614544',
    projectId: 'mmail-1e27d',
    storageBucket: 'mmail-1e27d.firebasestorage.app',
    iosBundleId: 'com.example.mewmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUl-wYyUNTi3axuAK0BJXU-G_gpG_KF6M',
    appId: '1:164434614544:web:574d2130b7f9942c8a6d95',
    messagingSenderId: '164434614544',
    projectId: 'mmail-1e27d',
    authDomain: 'mmail-1e27d.firebaseapp.com',
    storageBucket: 'mmail-1e27d.firebasestorage.app',
    measurementId: 'G-XKYJ5BJTKJ',
  );
}
